services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    volumes:
      - /var/www/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: steve12345
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: steve12345
      MYSQL_ROOT_PASSWORD: Meopham12345!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
   db_data:
